[tool.black]
line-length = 88
extend-exclude = """(\
  taskcluster/scripts/external_tools)\
  """

[tool.pytest.ini_options]
xfail_strict = true

[tool.coverage.run]
parallel = true
branch = true
source = ["src/taskgraph/", "taskgraph", "src/taskgraph/run-task/"]

[tool.ruff]
select = [
    "E", "W",       # pycodestyle
    "F",            # pyflakes
    "I",            # isort
    "PLC", "PLE",   # pylint
    "UP",           # pyupgrade
]
ignore = [
    "E402",
    "E501",  # let black handle line-length
    "E741",
]
target-version = "py37"
exclude = [
  "src/taskgraph/run-task/robustcheckout.py",
  "taskcluster/scripts/external_tools/tooltool.py",
]
extend-include = [
  # run-task is a python file, but doesn't have an extension
  "src/taskgraph/run-task/run-task"
]

[tool.ruff.isort]
known-first-party = ["taskgraph"]
